### ISSUE TITLE
HDMI black screen

### ISSUE THREAD

**Issue by nypdmax** [yqlbu/asus-b460i-strix-oc-efi#1]
Hi @yqlbu , thx for the awesome work!

I changed the config.plist a bit to drive my 27' 2560x1440 monitor with the builtin HD630.
I have successfully installed macOS big sur.

The only issue I have is, every time the login screen pops up, my monitor goes black and I have to unplug & re-plug the HDMI cable. How can I fix it? 

My setup:
CPU: intel i7-10700
Mobo: Strix-b460i
Memory: Kingston DDR4 8GB 2933 mHz x2
SSD: WD SN750 500GB
Graphics card: intel HD 630 

PS: Is it okay to upgrade my os to the latest Monterey without changing any settings (e.g., OpenCore, EFI)?

**Comment by piyoki** [comment]
I would recommend going with DP instead of HDMI as it is much more compatible. The EFI works for a dedicated GPU, in my case, I am using 5500XT. On the other hand, I think it should be fine if you upgrade to Monterey. I am currently running Monterey 12.1 with the latest EFI, and it works flawlessly. I plan to update the EFI next week, so stay tuned!

**Comment by nypdmax** [comment]
Thx, Im using Monterey 12.2 now.
Btw, adding igfxonln=1 to boot args fixed the HDMI black screen issue.

**Comment by piyoki** [comment]
Good to know!
